name: 'Drat upload'
author: 'Mike Mahoney (@mikemahoney218)'
description: 'Upload an R package to a personal drat repository'
inputs:
  package:
    description: 'The GitHub repository for the package to upload'
    default: ${{ github.repository }}
    required: true
  drat_repo:
    description: "The GitHub repository for the drat repo to update"
    required: true
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
    required: true
  commit_message: 
    description: "The commit message to use when updating the drat repo"
    required: true
    default: "Automated update"
  commit_author: 
    description: "The author to write the commit as"
    required: true
    default: "Drat Updater"
  commit_email: 
    description: "The email to associate the commit with"
    required: true
  prune: 
    description: >
      Boolean: if `true`, this will run `pruneRepoForAllRversions()` after
      updating the repository.
    default: false
    required: true
  archive: 
    description: >
      Boolean: if `true`, this will run `archivePackages()` after
      updating the repository.
    default: false
    required: true
    
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        path: package
        token: "${{ inputs.token }}"

    - uses: actions/checkout@v4
      with: 
        repository: "${{ inputs.drat_repo }}"
        token: "${{ inputs.token }}"
        path: drat

    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: 'release'

    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        working-directory: package

    - run: |
        R -e "pak::pkg_install(c('drat', 'knitr'))"
        R CMD build package
        R -e 'drat::insertPackage(list.files(pattern = ".tar.gz$")[[1]], "drat")'
        if [ "${{ inputs.archive }}" = 'true' ]; then
          R -e 'drat::archivePackages("drat")'
        fi
        if [ "${{ inputs.prune }}" = 'true' ]; then
          R -e 'drat::pruneRepoForAllRversions("drat")'
        fi
        R -e 'drat::updateRepo("drat")'
        cd drat
        git add .
        git config --global user.email "${{ inputs.commit_email }}"
        git config --global user.name "${{ inputs.commit_author }}"
        git commit -am "${{ inputs.commit_message }}"         
        git push "https://${{ inputs.token }}@github.com/${{ inputs.drat_repo }}"
      shell: bash
branding:
  icon: 'box'  
  color: 'purple'
